version: '2'

services:
    phpmyadmin:
      image: corbinu/docker-phpmyadmin
      ports:
        - "80"
      links:
        - db:mysql
      environment:
        - MYSQL_USERNAME: root
        - MYSQL_PASSWORD: password1
    db:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD: password1
      volumes:
        - "dbdata:/var/lib/mysql"
        
volumes:
  dbdata:
    driver: solidfire
    driver_opts:
      size: 10
      type: gold