version: '2'

services:
    db:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD: password1
      volumes:
        - "dbdata:/var/lib/mysql"
        
volumes:
  dbdata:
    driver: solidfire
    driver_opts:
      size: 10
      type: gold