apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels: 
    name: mariadb
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: mariadb:latest
      name: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password1
      ports: 
        - containerPort: 3306
          name: mariadb
