apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels: 
    name: wordpress
spec: 
  containers: 
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: password1
      ports: 
        - containerPort: 80
          name: wordpress
