apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels: 
    name: wordpress
spec: 
  containers: 
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password1
        - name: WORDPRESS_DB_NAME
          value: wordpress
      ports: 
        - containerPort: 80
          name: wordpress
